### ISSUE TITLE
HTML element is not defined 

### ISSUE THREAD

**Issue by Erildo** [jerosoler/wave-audio-path-player#1]
While using sveltekit, after installation with npm i ... I get the following error:
HTML element is not defined  at HTMLElement{constructor(){super();$(this,"loadSong",()=>{this.durati
can you please take a look at it

**Comment by jerosoler** [comment]
When does this error occur?

in the build?

**Comment by Erildo** [comment]
this one too is necessary to be imported through js file directly rather than install it through npm

**Comment by wrightwriter** [comment]
faced same issue in svelte without sveltekit, might be worth mentioning in description

**Comment by jerosoler** [comment]
Try https://stackoverflow.com/questions/74535890/in-svelte-and-vite-error-htmlelement-is-not-defined-shows-up-after-running-n

**Comment by wrightwriter** [comment]
hmm, actually sorry, importing worked fine in Svelte! The issue was, i couldn't pass any parameters to the webcomponent... they were undefined, so i hardcoded them in after cloning this repo.
Thanks for the work in any case, it's great!
